version: '3.8'

services:
  backend:
    build:
      context: ../kg-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    networks:
      - app-network
    environment:
      - GO_ENV=production
  
  frontend:
    build:
      context: ../kg-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge  

